name: fluentish
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  audioplayers: ^6.7.1

  flutter_map: ^8.3.1
  geolocator: ^14.0.3
  google_fonts: ^8.1.0
  google_maps_flutter: ^2.17.1
  latlong2: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.gif
    - assets/images/fluentish_logo.png
    - assets/images/friends/
    - assets/google_fonts/
    - assets/images/
    - assets/audio/
