name: fluentish
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  audioplayers: ^6.7.1
  cloud_firestore: ^6.7.1
  firebase_auth: ^6.5.6
  firebase_core: ^4.12.1
  firebase_core_platform_interface: ^8.0.0
  firebase_messaging: ^16.4.3
  firebase_storage: ^13.4.5
  flutter:
    sdk: flutter
  flutter_map: ^8.3.1
  geohash_plus: ^1.1.1
  geolocator: ^14.0.3
  google_fonts: ^8.1.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.3
  latlong2: ^0.10.1
  google_mlkit_translation: ^0.12.0
  mockito: ^5.6.4
  plugin_platform_interface: ^2.1.8
  url_launcher: ^6.3.2
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.gif
    - assets/images/fluentish_logo.png
    - assets/images/friends/
    - assets/google_fonts/
    - assets/images/
    - assets/audio/
