// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCStCUCI64x6JJQykCT1vNvDMeHjx-mdi8',
    appId: '1:794059461770:web:2b47cbe5b07e596872c973',
    messagingSenderId: '794059461770',
    projectId: 'fluentish-9d857',
    authDomain: 'fluentish-9d857.firebaseapp.com',
    storageBucket: 'fluentish-9d857.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-pVl86SH8kE-sWVCjd_A7-8ghUge0cGY',
    appId: '1:794059461770:android:e77186c2935fbdbc72c973',
    messagingSenderId: '794059461770',
    projectId: 'fluentish-9d857',
    storageBucket: 'fluentish-9d857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdFWjIqjHq3giXxWbePA8pkcs1Il5iXE',
    appId: '1:794059461770:ios:1052b6fcfa43f3c372c973',
    messagingSenderId: '794059461770',
    projectId: 'fluentish-9d857',
    storageBucket: 'fluentish-9d857.firebasestorage.app',
    iosBundleId: 'com.example.fluentish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcdFWjIqjHq3giXxWbePA8pkcs1Il5iXE',
    appId: '1:794059461770:ios:380bff24bce5fc4e72c973',
    messagingSenderId: '794059461770',
    projectId: 'fluentish-9d857',
    storageBucket: 'fluentish-9d857.firebasestorage.app',
    iosBundleId: 'com.fluentish.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCStCUCI64x6JJQykCT1vNvDMeHjx-mdi8',
    appId: '1:794059461770:web:b59c51ef0533bf5672c973',
    messagingSenderId: '794059461770',
    projectId: 'fluentish-9d857',
    authDomain: 'fluentish-9d857.firebaseapp.com',
    storageBucket: 'fluentish-9d857.firebasestorage.app',
  );
}
